global:
  resolve_timeout: 5m

route:
  receiver: accountia-webhook
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: accountia-webhook
    webhook_configs:
      - url: http://localhost:3000/api/alerts
        send_resolved: true
