global:
  scrape_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

scrape_configs:
  - job_name: 'accountia-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:4789']

  - job_name: 'accountia-web'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'accountia-ai'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
