sonar.projectKey=accountia-web
sonar.projectName=Accountia Web
sonar.projectVersion=1.0
sonar.sources=app,components,actions,hooks,lib,stores,types,proxy.ts,get-dictionary.ts,i18n-config.ts
# sonar.tests=test (no test directory in this project)
# sonar.test.inclusions=test/**/*.test.tsx,test/**/*.test.ts
sonar.exclusions=node_modules/**,.next/**,public/**,test/**,**/*.test.tsx,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=4096
sonar.typescript.tsconfigPath=tsconfig.sonar.json