import { env } from '@/env';

export const API_CONFIG = {
  BASE_URL: env.NEXT_PUBLIC_BACKEND ?? 'http://127.0.0.1:4789/api',
  AUTH: {
    REGISTER: 'auth/register',
    LOGIN: 'auth/login',
    LOGOUT: 'auth/logout',
    REFRESH: 'auth/refresh',
    FORGOT_PASSWORD: 'auth/forgot-password',
    RESET_PASSWORD: 'auth/reset-password',
    CONFIRM_EMAIL: 'auth/confirm-email/{token}',
    FETCH_USER: 'auth/fetchuser',
    FETCH_USER_BY_ID: 'auth/fetchuserbyid',
    UPDATE: 'auth/update',
    DELETE: 'auth/delete',
    RESEND_CONFIRMATION: 'auth/resend-confirmation-email',
    FETCH_ALL_USERS: 'auth/users',
    DELETE_USER_BY_ADMIN: 'auth/users/{id}',
    CHANGE_ROLE: 'auth/change-role',
    TWO_FA_SETUP: 'auth/2fa/setup',
    TWO_FA_VERIFY: 'auth/2fa/verify',
    TWO_FA_DISABLE: 'auth/2fa/disable',
    TWO_FA_LOGIN: 'auth/2fa/login',
    BAN_USER: 'auth/users/{id}/ban',
    UNBAN_USER: 'auth/users/{id}/unban',
    GOOGLE: 'auth/google',
    GOOGLE_EXCHANGE: 'auth/google/exchange',
    GOOGLE_CALLBACK: 'auth/google/callback',
    STRIPE_ONBOARDING: 'auth/stripe/onboarding',
    STRIPE_STATUS: 'auth/stripe/status',
  },
  BUSINESS: {
    APPLY: 'business/apply',
    APPLICATIONS: 'business/applications',
    REVIEW_APPLICATION: 'business/applications/{id}/review',
    MY_BUSINESSES: 'business/my-businesses',
    ALL_BUSINESSES: 'business/all',
    GET_BUSINESS: 'business/details',
    UPDATE_BUSINESS: 'business/update',
    DELETE_BUSINESS: 'business/delete',
    ASSIGN_USER: 'business/users',
    UNASSIGN_USER: 'business/users/{userId}',
    TENANT_METADATA: 'business/tenant/metadata',
    GET_CLIENTS: 'business/clients',
    CHANGE_CLIENT_ROLE: 'business/{id}/clients/{clientId}/role',
    DELETE_CLIENT: 'business/clients/{clientId}',
    GET_STATISTICS: 'business/statistics',
    GET_CLIENT_PODIUM: 'business/client-podium',
    GET_OTHER_BUSINESSES: 'business/other',
    INVITE_USER: 'business/invites',
    RESEND_INVITE: 'business/invites/resend',
    GET_PENDING_INVITES: 'business/invites/pending',
    REVOKE_INVITE: 'business/invites/{inviteId}',
    STRIPE_ONBOARDING_LINK: 'business/stripe/onboarding-link',
    STRIPE_STATUS: 'business/stripe/status',
    GET_TEAM: 'business/team',
  },
  PRODUCTS: {
    CREATE: 'products',
    LIST: 'products',
    GET: 'products/{id}',
    UPDATE: 'products/{id}',
    DELETE: 'products/{id}',
    IMPORT: 'products/import',
    STOCK_INSIGHTS: 'products/stock-insights',
    BULK_DELETE: 'products/bulk-delete',
  },
  INVOICES: {
    // Issuer Endpoints
    CREATE: 'invoices',
    LIST_ISSUED: 'invoices/issued',
    GET_ISSUED: 'invoices/issued/{id}',
    UPDATE_ISSUED: 'invoices/issued/{id}',
    TRANSITION: 'invoices/issued/{id}/transition',
    IMPORT: 'invoices/import',
    IMPORT_TEMPLATE: 'invoices/import/template',
    IMPORT_DOCUMENT: 'invoices/import/document',
    // Recipient Endpoints
    LIST_RECEIVED_BUSINESS: 'invoices/received/business',
    LIST_RECEIVED_INDIVIDUAL: 'invoices/received/individual',
    GET_RECEIVED_DETAILS: 'invoices/received/{receiptId}/details',
    GET_RECEIVED_INDIVIDUAL_DETAILS:
      'invoices/received/individual/{receiptId}/details',
    CREATE_INDIVIDUAL_CHECKOUT:
      'invoices/received/individual/{receiptId}/payments/checkout',
    CREATE_INDIVIDUAL_MOCK_PAYMENT:
      'invoices/received/individual/{receiptId}/payments/mock',
    CONFIRM_PAYMENT: 'invoices/payments/confirm',
  },
  CHAT: {
    SEND_MESSAGE: 'chat/message',
  },
  NOTIFICATIONS: {
    GET_NOTIFICATIONS: 'notifications',
    MARK_AS_READ: 'notifications/{id}/read',
    MARK_ALL_AS_READ: 'notifications/read-all',
  },
  AUDIT: {
    GET_LOGS: 'audit',
  },
  HEALTH: {
    CHECK: 'health',
  },
  REPORTS: {
    VAT: 'reports/vat',
  },
  COMMENTS: {
    CREATE: 'comments',
    LIST: 'comments',
    UPDATE: 'comments/{id}',
    DELETE: 'comments/{id}',
  },
  EXPENSES: {
    CREATE: 'expenses',
    LIST: 'expenses',
    SUMMARY: 'expenses/summary',
    GET: 'expenses/{id}',
    UPDATE: 'expenses/{id}',
    SUBMIT: 'expenses/{id}/submit',
    REVIEW: 'expenses/{id}/review',
    REIMBURSE: 'expenses/{id}/reimburse',
    DELETE: 'expenses/{id}',
    EXTRACT_RECEIPT: 'expenses/extract-receipt',
  },
  RECURRING_INVOICES: {
    CREATE: 'recurring-invoices',
    LIST: 'recurring-invoices',
    GET: 'recurring-invoices/{id}',
    UPDATE: 'recurring-invoices/{id}',
    DELETE: 'recurring-invoices/{id}',
  },
  ANALYTICS: {
    DASHBOARD: 'analytics/dashboard',
  },
  VENDORS: {
    CREATE: 'vendors',
    LIST: 'vendors',
    GET: 'vendors/{id}',
    UPDATE: 'vendors/{id}',
    DELETE: 'vendors/{id}',
  },
  PURCHASE_ORDERS: {
    CREATE: 'purchase-orders',
    LIST: 'purchase-orders',
    GET: 'purchase-orders/{id}',
    UPDATE: 'purchase-orders/{id}',
    SUBMIT: 'purchase-orders/{id}/submit',
    APPROVE: 'purchase-orders/{id}/approve',
    RECEIVE: 'purchase-orders/{id}/receive',
    DELETE: 'purchase-orders/{id}',
  },
  COLLECTIONS: {
    DASHBOARD: 'collections/dashboard',
    RISK_SCORES: 'collections/risk-scores',
    GENERATE_REMINDER: 'collections/invoices/{id}/generate-reminder',
  },
  CLIENT_PORTAL: {
    GENERATE_TOKEN: 'client-portal/generate-token',
    VERIFY: 'client-portal/verify/{token}',
    INVOICES: 'client-portal/{token}/invoices',
    INVOICE_DETAIL: 'client-portal/{token}/invoices/{invoiceId}',
  },
  ACCOUNTANT: {
    CREATE_JOB: 'accountant/jobs',
    LIST_JOBS: 'accountant/jobs',
    GET_JOB: 'accountant/jobs/{taskId}',
    GET_JOB_RESULTS: 'accountant/jobs/{taskId}',
    GET_TAXES: 'accountant/taxes/{year}',
    CALCULATE_TAXES: 'accountant/taxes/{year}',
    HEALTH: 'accountant/health',
  },
} as const;
